### ISSUE TITLE
Circular import error between scout & account

### ISSUE THREAD

**Issue by Karmak23** [CommonsDev/dataserver#40]
Yo,

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/olive/.virtualenvs/uds/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/home/olive/.virtualenvs/uds/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/olive/.virtualenvs/uds/lib/python2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
    mw_instance = mw_class()
  File "/home/olive/.virtualenvs/uds/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/home/olive/.virtualenvs/uds/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olive/.virtualenvs/uds/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/olive/.virtualenvs/uds/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/olive/sources/unisson-dataserver/dataserver/urls.py", line 8, in <module>
    from accounts.api import UserResource, GroupResource, ProfileResource, ObjectProfileLinkResource
  File "/home/olive/sources/unisson-dataserver/accounts/api.py", line 30, in <module>
    from scout.api import PlaceResource
  File "/home/olive/sources/unisson-dataserver/scout/api.py", line 22, in <module>
    from accounts.api import UserResource
ImportError: cannot import name UserResource
```

I will remove the import on scout from account.api and use a `'scout.api.MapResource'` string.

I think the user/account module should depend on nothing or a very few things, because every other module is likely to depend on it at some point, and this will create other circular dependancies.

I will patch my feature branch for now, to acheive a running IP2IS migration, thus this patch will make its way into the dataserver in next release (likely 1.6 with other migration-related changes).

Everyone OK ? 

Currently, the fix is a no-op change, but I request team agreement on the no-or-minimal-deps in the account module principle.

**Comment by glibersat** [comment]
:+1:

**Comment by freddylimpens** [comment]
Agreed.
